# --- DB Connection---
spring.datasource.url=jdbc:postgresql://localhost:5432/spring_db
spring.datasource.username=spring_user
spring.datasource.password=developerPass
# --------------------

# --- Cloudinary ---
#cloudinary.cloud_name=dlzisichg
#cloudinary.api_key=559146148458554
#cloudinary.api_secret=zPBfls9QcSUdEHO_kQTKSfpblLk
# --------------------

CLOUDINARY_URL=cloudinary://559146148458554:zPBfls9QcSUdEHO_kQTKSfpblLk@dlzisichg

spring.jpa.hibernate.ddl-auto=create
# server.forward-headers-strategy=framework
