spring.application.name=Employee Management App

# --- DB Connection ---
spring.datasource.url=jdbc:postgresql:<Database>
spring.datasource.username=<User>
spring.datasource.password=<Password>
# --------------------

# --- Cloudinary ---
CLOUDINARY_URL=cloudinary://<api_key>:<api_secret>@<api_cloud_name>
# --------------------

# --- JWT Configuration ---
jwt.secret=<jwt-secret>
jwt.expiration-ms=<ms-time-value>
# --------------------

spring.servlet.multipart.max-file-size=10MB
spring.main.allow-bean-definition-overriding=true
spring.profiles.active=dev
spring.jpa.hibernate.ddl-auto=update