spring.application.name=Employee Management App

# --- DB Connection---
spring.datasource.url=jdbc:postgresql:<Database>
spring.datasource.username=<User>
spring.datasource.password=<Password>
# --------------------

spring.profiles.active=dev
spring.jpa.hibernate.ddl-auto=update